include: package:flutter_lints/flutter.yaml
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - close_sinks
    - annotate_overrides
    - hash_and_equals
    - prefer_is_not_empty
    - package_api_docs
    - type_annotate_public_apis
    - library_private_types_in_public_api