name: disposer
description: It's a simple interface to manage all instances that needs to been disposed. Pagacke can generate feature module with `Disposable`
version: 0.0.8
homepage: null
repository: https://github.com/damienissa/disposer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

executables:
  disposer:

dependencies:
  args: ^2.3.0  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null